#!/bin/bash
set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────────
# Part 0 – Select Certificate Type (PIN or PAN)
#
# Determines which Apple transport certificate will be used throughout the
# entire key-import flow (Parts 1–4).
#
#   PIN  → transport-key-certificate-PIN-NON_PROD.pem
#          Used for PIN block encryption (KEK for PIN data).
#
#   PAN  → transport-key-certificate-PAN-NON_PROD.pem
#          Used for cardholder / PAN data encryption (KEK for cardholder data).
#
# This script can be run interactively (no arguments) or non-interactively:
#   ./0-setup-cert-type.sh PIN
#   ./0-setup-cert-type.sh PAN
#
# Outputs:
#   session-config.env  – Shell variables to be sourced by subsequent steps
#                         (CERT_FILE, DATA_TYPE, REGION, SIG_HEADER)
# ──────────────────────────────────────────────────────────────────────────────

OUTPUT_ENV="session-config.env"

CERT_PIN="transport-key-certificate-PIN-NON_PROD.pem"
CERT_PAN="transport-key-certificate-PAN-NON_PROD.pem"

SIG_HEADER_CARDHOLDER="3130303030545041454159"   # "10000TPAEAY" – cardholder data KEK
SIG_HEADER_PIN="3130303030545041454959"          # "10000TPAEIY" – PIN KEK

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
ok()   { echo -e "  ${GREEN}[OK]${NC}  $*"; }
fail() { echo -e "  ${RED}[FAIL]${NC} $*"; exit 1; }
info() { echo -e "  ${YELLOW}[INFO]${NC} $*"; }

echo "======================================================"
echo " Step 0 – Certificate Type Selection"
echo "======================================================"
echo ""

# ── Determine DATA_TYPE ────────────────────────────────────────────────────
if [ -n "${1:-}" ]; then
    DATA_TYPE="${1}"
else
    echo -e "  ${CYAN}Which type of transport certificate do you want to use?${NC}"
    echo ""
    echo "    [1] PAN  – KEK for cardholder / PAN data"
    echo "    [2] PIN  – KEK for PIN block encryption"
    echo ""
    read -rp "  Enter your choice (1 or 2): " CHOICE

    case "$CHOICE" in
        1) DATA_TYPE="PAN" ;;
        2) DATA_TYPE="PIN" ;;
        *) fail "Invalid choice: '$CHOICE'. Please enter 1 or 2." ;;
    esac
fi

# ── Normalise and validate DATA_TYPE ──────────────────────────────────────
DATA_TYPE=$(echo "$DATA_TYPE" | tr '[:lower:]' '[:upper:]')

case "$DATA_TYPE" in
    PIN) CERT_FILE="$CERT_PIN" ; SIG_HEADER="$SIG_HEADER_PIN" ;;
    PAN) CERT_FILE="$CERT_PAN" ; SIG_HEADER="$SIG_HEADER_CARDHOLDER" ;;
    *)   fail "Unknown type: '$DATA_TYPE'. Accepted values: PIN | PAN." ;;
esac

# ── Validate certificate file exists ──────────────────────────────────────
[ -f "$CERT_FILE" ] || fail "Certificate file not found: $CERT_FILE"

CERT_SUBJECT=$(openssl x509 -noout -subject -in "$CERT_FILE" 2>/dev/null \
    | sed 's/subject=//' || echo "(could not parse subject)")

REGION="${2:-us-east-1}"

ok "Type selected  : $DATA_TYPE"
ok "Certificate    : $CERT_FILE"
ok "Subject        : $CERT_SUBJECT"
ok "SIG_HEADER     : $SIG_HEADER"
ok "Region         : $REGION"

# ── Write session-config.env ───────────────────────────────────────────────
cat > "$OUTPUT_ENV" << EOF
# Generated by 0-setup-cert-type.sh – $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Source this file before running subsequent steps:
#   source ./$OUTPUT_ENV

export DATA_TYPE="$DATA_TYPE"
export CERT_FILE="$CERT_FILE"
export SIG_HEADER="$SIG_HEADER"
export REGION="$REGION"
EOF

echo ""
ok "Configuration saved to: $OUTPUT_ENV"
echo ""
echo "======================================================"
echo " To proceed, run the following steps in order:"
echo "======================================================"
echo ""
echo -e "  ${CYAN}source ./$OUTPUT_ENV${NC}"
echo -e "  ${CYAN}./1-import_apple_transport_key.sh${NC}"
echo -e "  ${CYAN}./2-generate_rsa_key_pair.sh${NC}"
echo -e "  ${CYAN}./3-generate_kek.sh${NC}"
echo -e "  ${CYAN}./4-sign_encrypted_kek.sh${NC}"
echo ""
